### ISSUE TITLE
Work with bookmarks?

### ISSUE THREAD

**Issue by coredumperror** [sblask/webextension-open-tabs-in-foreground#1]
Is there a way to make this work on Bookmarks as well as links? Ever since the latest Chrome update, my previous solution for foreground tabs (Tabs to the front!) has broken entirely, and this is the only thing that works to make tabs open in the foreground. But I'd really like it to work on tabs opened from bookmarks, too.

**Comment by sblask** [comment]
Not possible unfortunately...

**Comment by coredumperror** [comment]
Dang. Oh well.
