### ISSUE TITLE
Extension fails to open new tabs next to the current tab...

### ISSUE THREAD

**Issue by jtbrown3** [sblask/webextension-open-tabs-in-foreground#2]
### Issue Description
On Latest Chrome Browser for Windows:  This extension does not open new tabs next to the current tab. Instead, it opens new tabs at the end of the tab bar.  This is a deviation from the normal Chrome browser behavior.

I'd suggest that the default behavior is changed to open new tabs NEXT to the current tab.  OR, provide an option to open it at the end of the tab bar.

**Comment by sblask** [comment]
I've got an different extension for that behaviour: https://chrome.google.com/webstore/detail/open-tabs-next-to-current/gmpnnmonpnnmnhpdldahlekfofigiffh

I just checked, the normal behaviour is not changed, what you're experience is the default.
