### ISSUE TITLE
Doesn't work on Mac Version 71.0.3578.98 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by briantully** [sblask/webextension-open-tabs-in-foreground#3]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Ctrl-clicking links and selecting "open link in new tab" opens the tab in the background.

**Comment by sblask** [comment]
Opening a link from the context menu is not supported, only clicking links directly.
