### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by illustribe** [sblask/webextension-open-tabs-in-foreground#4]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [X] Chrome

### What is your operating system?

- [ ] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
Hello,
The extension is not working as it's described in the overview. With cmd+click, tabs are still opening in the background.

I hope this can be fixed as it is a very useful extension! ;)

Thank you very much 😊 

BTW, I'm on Chrome Version 75.0.3745.4 (Official Build) dev (64-bit), Mac OS 10.13.6

**Comment by sblask** [comment]
I am not a Mac user, might be apple + click ?

**Comment by illustribe** [comment]
What I meant is that with cmd+click (that'd be ctrl+click in windows) AND with cmd+shift+click (that'd be ctrl+shift+click) BOTH are opening the tabs IN the foreground ^^

**Comment by sblask** [comment]
Just tested with Firefox 66 and use it with Chrome every day. I don't have a problem. Might be because you are using the dev version of Chrome, I am at version 73.

**Comment by illustribe** [comment]
Yes it might be so. I guess I'll have to consider switch to normal chrome version. Thank you and is good to know it's working well, great job!! ;)
